# Generated by Django 5.2 on 2025-05-12 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0002_alter_car_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='car',
            name='price',
        ),
    ]
