# Generated by Django 5.2 on 2025-05-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0003_remove_car_created_by_remove_car_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='rental_price',
            field=models.IntegerField(default=23, max_length=5),
            preserve_default=False,
        ),
    ]
