# Generated by Django 5.2 on 2025-05-14 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0005_car_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_type',
            field=models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'Suv'), ('truck', 'Truck')], default='Sedan', max_length=10),
        ),
    ]
