# Generated by Django 5.2 on 2025-05-15 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0010_alter_booking_booking_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='name',
        ),
    ]
